spring:
  data:
    mongodb:
      host: localhost
      port: 27025
      database: test
      username: test
      password: test
logging:
  level:
    root: info
    org.hibernate.SQL: TRACE
    org.springframework.data.mongodb.core.MongoTemplate: TRACE
    org.springframework.boot.autoconfigure: ERROR